sudo: false
language: python
python:
  - '3.6'
before_script:

  - wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2
  - tar jxvf samtools-1.9.tar.bz2
  - cd samtools-1.9/htslib-1.9 && ./configure && make && sudo make install 
  - cd ../ && ./configure --without-curses && make && sudo make install && cd ../
                        
  - pip install requests
  - pip install scipy==1.1.0
  - pip install statistics==1.0.3.5
  - pip install pysam==0.15.2
  - pip install numpy==1.15.1

  - export HTSLIB_LIBRARY_DIR="/usr/local/lib"
  - export HTSLIB_INCLUDE_DIR="/usr/local/include"

  - wget https://github.com/pysam-developers/pysam/archive/v0.15.2.tar.gz
  - tar zxvf v0.15.2.tar.gz
  - cd pysam-0.15.2 && python setup.py build install && cd ..

  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/usr/local/lib"

script:
  - pip install .
  - python setup.py tests
  - python -m unittest
notifications:
  emails:
    - kchiba@hgc.jp
  on_success: change
  on_failure: always
